IGAPP-457: Try to prevent oom errors during android builds
Integreat/integreat-app pull request #149
Opened 2021-02-08 12:13 UTC by klinzo

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

I obviously do not know whether this is enough to prevent these errors due to oom.
Possible solution is from here, maxWorkers is already set: https://stackoverflow.com/questions/56002938/reactnative-0-59-x-build-fails-on-circleci-with-exit-value-137
Possibly more infos: 
https://circleci.com/blog/how-to-handle-java-oom-errors/
and another approach we could try if this does not work:
https://medium.com/@stevewestwood/building-android-projects-on-circleci-using-their-machine-executor-b731b386a12d

2021-02-08 22:13 UTC, Znippet approved these changes

2021-02-09 11:21 UTC, maxammann requested changes

2021-02-09 11:21 UTC, maxammann commented on .circleci/src/@common.yml
> +GRADLE_OPTS: '-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"'
These variables should be put to the circleci jobs where they are used. Also they seem a bit weird as `org.gradle.jvmargs` and `JAVA_OPTS` is set. What should gradle choose?

We already configure this in Fastfiles: https://github.com/Integreat/integreat-app/blob/51a2f5f9db596569f639144ee9b0a932851d7eaa/native/android/fastlane/Fastfile#L55-L58

Also make sure to leave some memory for the node process (bundler). I would estimate it requires at least 500MB of ram.

2021-02-09 11:22 UTC, SteffiStuffel commented
Why haven't you set the maxWorkers in metro.config.js as suggested in the stackoverflow link you shared?

2021-02-09 11:29 UTC, SteffiStuffel commented
Where is defined ci should use the metro.config.ci.js ?

2021-02-09 11:32 UTC, maxammann commented
In the Fastfile I posted: EXTRA_PACKAGER_ARGS

2021-02-10 16:30 UTC, maxammann approved these changes

2021-02-10 17:59 UTC, merged