IGAPP-509: Tooltips are opened on click
Integreat/integreat-app pull request #256
Opened 2021-04-17 10:31 UTC by maxammann

…detection

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

2021-04-17 17:37 UTC, klinzo approved these changes
Eazzzzzzyyy :thinking: Seems to work nicely :+1:
The spacing for header navigation item is a little bit off, but even though it is because of tooltips I'll create a separate issue as this was already the case before.

2021-04-17 17:37 UTC, klinzo commented on web/src/modules/common/components/Tooltip.js
> +      border-left-color: #333;
Shouldn't we use a color from our theme?

2021-04-17 17:57 UTC, klinzo requested changes
Tested on Firefox and Chrome (Desktop) and Firefox (Mobile), seems like the tooltips are still opened on click on mobile.

2021-04-20 09:27 UTC, Taggotty approved these changes
Seems to work fine :)
However I wonder whether It is intentional, that longer text is cropped.
E.g. "Diese Seite ist nicht hilfr..."

2021-04-22 09:42 UTC, SteffiStuffel approved these changes

2021-04-22 10:37 UTC, klinzo commented
@maxammann you mentioned in the call yesterday that we decided to open tooltips on click on mobile anyway, I can't remember that. Do you have a link? I don't really like it tbh.

2021-04-23 16:13 UTC, maxammann commented
> @maxammann you mentioned in the call yesterday that we decided to open tooltips on click on mobile anyway, I can't remember that. Do you have a link? I don't really like it tbh.

Sadly I dont remember where, but tooltips work find on mobile. If we do not want to show them, then we would need a separate way of handling it on mobile. As they work fine on mobile I'd just keep them.

2021-04-24 08:27 UTC, klinzo approved these changes

2021-04-24 08:43 UTC, klinzo commented
I just find it weird that tooltips are opened on click on mobile, this is not the case on web as well, it only appears on hovering there. But I guess that is just my opinion as I don't know any websites having tooltips on mobile at all.

2021-04-25 13:15 UTC, maxammann commented
> Also: On small screens no tooltips are shown for the toolbar but tooltips are shown for the action items (search, location change, ...). Do you know why this is as it is? But this is also no new behavior, so nothing to fix here.

Looks fine for me, I already fixed some spacing there.

2021-04-25 14:30 UTC, merged