IGAPP-610: Weird language item spacing if some are not available
Integreat/integreat-app pull request #268
Opened 2021-04-25 14:50 UTC by maxammann

… text when hovering

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

2021-04-25 14:50 UTC, maxammann commented
This PR also fixes an issue with the hover effect. If you hover an element it becomes bold and increases the width. The BoldSpacer fixes this jumping.

2021-04-25 14:52 UTC, maxammann commented
I also increased the max width of tooltip content

2021-04-26 06:48 UTC, SteffiStuffel approved these changes

2021-04-26 06:51 UTC, SteffiStuffel commented
Tested on Chrome

2021-04-26 08:34 UTC, klinzo approved these changes
I think you could add a release note for this :)

One minor observation: The tooltip for chinese (http://0.0.0.0:9000/testumgebung/de/news/local/157) was hidden behind the langauage change icon for me once, but I was not able to reproduce it again :/ So I think you can just ignore it.

2021-04-26 08:34 UTC, klinzo commented on web/src/modules/common/components/Selector.js
> +    props.enabled ? `color: ${props.theme.colors.textColor};` : `color: ${props.theme.colors.textDisabledColor};`}
```suggestion
  color: ${props => props.enabled ? props.theme.colors.textColor : props.theme.colors.textDisabledColor};
```

2021-04-26 08:34 UTC, klinzo commented on web/src/modules/common/components/Selector.js
> +}
I think this bracket is to much:
```suggestion
```

2021-04-26 08:34 UTC, klinzo commented on web/src/modules/common/components/Tooltip.js
> +}
```suggestion
  className?: string,
  ...
}
```

2021-04-26 08:34 UTC, klinzo commented on web/src/modules/common/components/Tooltip.js
> +// eslint-disable-next-line flowtype/require-exact-type
```suggestion
```

2021-04-27 09:03 UTC, Taggotty requested changes
I get the following error in the web console: `Warning: Received 'true' for a non-boolean attribute 'enabled'.`

2021-04-27 09:44 UTC, klinzo commented
> I get the following error in the web console: `Warning: Received 'true' for a non-boolean attribute 'enabled'.`

I think we had this already, the reason are styled component props if I remember corectly: https://styled-components.com/docs/api#transient-props

2021-05-02 13:31 UTC, maxammann commented
@klinzo I imporoved the positioning of tooltips

2021-05-03 07:25 UTC, klinzo approved these changes
Tested, looks really good!

2021-05-04 08:03 UTC, Taggotty approved these changes
For the language tooltip I still get an overflow on the right side. Personally I think that is no big problem, but if you find a quick fix I am also content :)
<img src="https://user-images.githubusercontent.com/28013368/116975309-baf0b400-acbf-11eb-9e7f-ec1404083448.jpg" height="400"/>

2021-05-17 07:40 UTC, maxammann commented
> For the language tooltip I still get an overflow on the right side. Personally I think that is no big problem, but if you find a quick fix I am also content :)


Fixed, missed to remove a `/2`

2021-05-17 08:28 UTC, merged