IGAPP-580: Remove link replacement for tuNews in native
Integreat/integreat-app pull request #280
Opened 2021-05-04 12:47 UTC by Znippet

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

Tested with  `tunewsApiBaseUrl` constant with https://tunews-test.integreat-app.de, see https://issues.tuerantuer.org/browse/IGAPP-592

2021-05-04 12:54 UTC, klinzo requested changes
Yeah right, we already support HTML there. I think this breaks the linking replacement functionality for local news though as this component is used there as well. I think we have to think about another solution. Not tested though.

2021-05-05 08:58 UTC, Taggotty commented
> Yeah right, we already support HTML there, did not think about that see_no_evil . I think this breaks the linking replacement functionality for local news though as this component is used there as well. I think we have to think about another solution :/ Not tested though.

Why would this break the linking replacement?

2021-05-06 11:51 UTC, klinzo approved these changes
Okay, sorry again, not sure where I was mentally when I reviewed this for the first time :confused: 
So everything works as expected :+1: 
I think a test that html is actually rendered would be nice though.
Maybe you could just replace the tünews content in the test with e.g. the following:
`<main><p>ArbeitnehmerInnen in Quarant&#228;ne haben nicht zwangsl&#228;ufig frei. Das ist im Infektionsschutzgesetz und meist zus&#228;tzlich in Bestimmungen des Arbeitgebers genau geregelt. Nur wer in Quarant&#228;ne oder Absonderung &#8211; so hei&#223;t das im Beh&#246;rdendeutsch &#8211; tats&#228;chlich erkrankt, also krankgeschrieben ist, muss nicht arbeiten. Alle anderen m&#252;ssen je nach ihren Aufgabenbereichen und der vom Arbeitgeber gestellten technischen Ausstattung auch in Quarant&#228;ne ihrer Besch&#228;ftigung nachgehen. ArbeitnehmerInnen die normalerweise an Maschinen oder in Laboren arbeiten, k&#246;nnen von ihrem Arbeitgeber auch andere Aufgaben zugeteilt bekommen, die sie dann zuhause erledigen m&#252;ssen.</p>\n<p>tun21033101</p>\n<p>Wer in Corona-Quarant&#228;ne muss, hat verschiedene Regeln zu beachten. Das gilt auch f&#252;r arbeitsrechtliche Fragen. Foto: t&#252;news INTERNATIONAL / Martin Klaus.</p>\n<h1><a href="https://tunewsinternational.com/category/corona-deutsch/">Aktuelle Informationen zu Corona: Hier klicken</a></h1>\n</main>\n"`
Then you could assert e.g.
``` js
    expect(getByText(tuNews.title)).toBeTruthy()
    expect(getByText('ArbeitnehmerInnen in Quarantäne haben nicht zwangsläufig frei. Das ist im Infektionsschutzgesetz und meist zusätzlich in Bestimmungen des Arbeitgebers genau geregelt. Nur wer in Quarantäne oder Absonderung – so heißt das im Behördendeutsch – tatsächlich erkrankt, also krankgeschrieben ist, muss nicht arbeiten. Alle anderen müssen je nach ihren Aufgabenbereichen und der vom Arbeitgeber gestellten technischen Ausstattung auch in Quarantäne ihrer Beschäftigung nachgehen. ArbeitnehmerInnen die normalerweise an Maschinen oder in Laboren arbeiten, können von ihrem Arbeitgeber auch andere Aufgaben zugeteilt bekommen, die sie dann zuhause erledigen müssen.')).toBeTruthy()
    expect(getByText('Aktuelle Informationen zu Corona: Hier klicken')).toBeTruthy()
    fireEvent.press(getByText('Aktuelle Informationen zu Corona: Hier klicken'))
    expect(navigateToLink).toHaveBeenCalledWith('https://tunewsinternational.com/category/corona-deutsch/', language, 'https://tunewsinternational.com/category/corona-deutsch/')
    expect(queryByText('https://tunewsinternational.com/category/corona-deutsch/')).toBeFalsy()
    expect(queryByText('<main>')).toBeFalsy()
```
You can use any other example of your choice as well of course or adapt this one, e.g. to assert other html attributes are rendered correctly as well.

2021-05-07 07:23 UTC, klinzo approved these changes

2021-05-09 07:16 UTC, Taggotty approved these changes

2021-05-09 07:54 UTC, merged