IGAPP-497: Snackbar on Failed Refresh
Integreat/integreat-app pull request #414
Opened 2021-09-01 09:29 UTC by Taggotty

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

2021-09-07 12:42 UTC, Taggotty commented
Not sure if that is what this issue wants, but it shows the snackbar if refresh should not be possible.

2021-09-07 12:42 UTC, Taggotty commented on native/src/routes/Settings.tsx
> -  const showSnackbar = (key: string) =>
was never used

2021-09-07 13:53 UTC, klinzo requested changes
Sadly this is not what the goal of the issue was. If the refresh fails because of no internet connection or for other reasons, the snackbar should be displayed and the old content is still displayed. Not sure how much effort to implement this is though.

2021-09-08 08:52 UTC, Taggotty commented
@klinzo thx for clarifying. Then i'll check out this case. The Payload provider really is confusing in this regard.

2021-09-08 09:38 UTC, klinzo commented
> @klinzo thx for clarifying. Then i'll check out this case. The Payload provider really is confusing in this regard.

Definitely! That's why there is also one issue to refactor it. Ugly af :vomiting_face: .

2021-09-08 09:40 UTC, klinzo approved these changes
Only approved to not block the merge later on once it is finished.

2021-09-21 09:17 UTC, closed without merging

2021-09-21 09:17 UTC, Taggotty commented
Didn't get any further than that. Probably needs quite a bit of refactoring.