IGAPP-831: Implemented different news preview lenghts
Integreat/integreat-app pull request #516
Opened 2021-11-22 20:49 UTC by Cmd190

The news preview length is now dependent from the viewport. 
Large Screen: 
![image](https://user-images.githubusercontent.com/75899673/142933201-eee64fc9-101a-467f-9072-3ad80eaac0cf.png)

Medium Screen:
![image](https://user-images.githubusercontent.com/75899673/142933277-ba5bb2c8-17ec-4012-8da6-1b8e46803308.png)

Small Screen:
![image](https://user-images.githubusercontent.com/75899673/142933143-e5ab10bc-7f65-4b76-9a20-4e49dd2c5b1d.png)

2021-11-23 10:13 UTC, klinzo requested changes
Please clean up the git history here :) Reset your local branch to master, cherry pick the relevant commits and force push.

Tested on phone and laptop on firefox

2021-11-23 10:13 UTC, klinzo commented on release-notes/2021.11.3/IGAPP-259-Add-contrast-for-setting-switches.yml
> +  - android
indentation, same in other release note

2021-11-23 10:13 UTC, klinzo commented on release-notes/unreleased/IGAPP-831-news.preview-length.yml
> +issue_key: IGAPP-259
```suggestion
issue_key: IGAPP-831
```

2021-11-23 10:13 UTC, klinzo commented on release-notes/unreleased/IGAPP-831-news.preview-length.yml
> +  - android
```suggestion
   - web
```

2021-11-23 10:13 UTC, klinzo commented on release-notes/unreleased/IGAPP-831-news.preview-length.yml
> +issue_key: IGAPP-259
Please also replace the dot `.` with a `-` in the file name

2021-11-23 10:13 UTC, klinzo commented on web/src/components/Tooltip.tsx
> +import dimensions from '../constants/dimensions'
Revert

2021-11-23 10:13 UTC, klinzo commented on web/src/constants/dimensions.ts
> +  mediumViewportBorderValue : number
```suggestion
  smallViewportThreshold : number
  mediumViewportThreshold : number
```

2021-11-23 10:13 UTC, klinzo commented on web/src/components/NewsListItem.tsx
> +      : NUM_OF_CHARS_ALLOWED_LARGE_SCREEN
If you change the order of the checks you can get rid of one check here

2021-11-23 10:13 UTC, klinzo commented on web/src/components/NewsListItem.tsx
> +const NUM_OF_CHARS_ALLOWED_SMALL_SCREEN = 100
Did you discuss these values with Nikola?

2021-11-23 10:17 UTC, SteffiStuffel reviewed
Not tested

2021-11-23 10:17 UTC, SteffiStuffel commented on web/src/components/NewsListItem.tsx
> +      : NUM_OF_CHARS_ALLOWED_LARGE_SCREEN
if think a `if..else if... else` would be much nicer than `if` and `?:` mixed.

```
if(width < small) {
  return SMALL_SCREEN
} else if (width < medium) {
  return MEDIUM_SCREEN
} else {
  return LARGE_SCREEN
}
```

2021-11-23 10:17 UTC, SteffiStuffel commented on web/src/components/Tooltip.tsx
> +import dimensions from '../constants/dimensions'
```suggestion
import dimensions from '../constants/dimensions'
```

2021-11-26 13:29 UTC, klinzo requested changes
May be bad UI/UX and should be rejected. Lets wait for some expertise here :)

2021-12-01 15:58 UTC, closed without merging

2021-12-01 15:59 UTC, Cmd190 commented
Our Designer claimed that this is not neccessary