IGAPP-97: Use webkit on ios
Integreat/integreat-app pull request #9
Opened 2020-09-30 17:56 UTC by Schedulaar

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **IGAPP**.

It seems Pois.js and PoisContainer.js had the wrong line-endings. I ended up converting them to LF. Not sure though, what happened exactly :see_no_evil:

2020-10-01 12:30 UTC, klinzo commented on native/src/modules/common/components/RemoteContent.js
> -        useWebKit={false}
🎉

2020-10-01 12:30 UTC, klinzo commented on native/src/modules/common/renderHtml.js
> +  console.debug('Resources to inject:') // TODO: remove
I think the TODO could be removed

2020-10-01 12:30 UTC, klinzo commented on native/src/routes/disclaimer/Disclaimer.js
> +                 resourceCacheUrl='http://localhost:8080'
Why did you choose to hardcode it here? Shouldn't you rather pass nothing? Just seems weird.

2020-10-01 12:30 UTC, klinzo commented on native/src/modules/static-server/containers/StaticServerProvider.js
> +    if (this.state.errorMessage != null) {
```suggestion
    if (this.state.errorMessage !== null) {
```

2020-10-01 14:12 UTC, klinzo requested changes
If I am clicking on a leaf category, safari opens localhost:8080 🤔 

Happens also for events, pois and disclaimer.

2020-10-02 21:11 UTC, Schedulaar commented
@klinzo Ahh.. Yeah, fortunately, I know why this happens 🙈 I just forgot to readd a line...
Could you test it on a real iOS device again, please? (Simulator never was a problem)

2020-10-05 09:30 UTC, klinzo commented
AFAICT it still opens the browser (localhost) :/

2020-10-15 04:47 UTC, klinzo approved these changes

2020-10-15 17:26 UTC, Taggotty approved these changes
Looks alright to me, although this is definitely not my field of expertise ^^

2020-10-16 07:51 UTC, klinzo commented on native/src/modules/common/components/RemoteContent.js
> +    const url = event.url.endsWith('/') ? event.url.slice(0, -1) : event.url
resourceCachUrl is `https://localhost:8080`, so if there is a query the check fails anyway, so I guess this should be fine. Right @Schedulaar ?

2020-10-16 13:43 UTC, Schedulaar commented on native/src/modules/common/components/RemoteContent.js
> +    const url = event.url.endsWith('/') ? event.url.slice(0, -1) : event.url
Yeah, but we should probably only use the normalized url for comparing below.
We should still use `this.props.onLinkPress(event.url)` imo

2020-10-16 14:04 UTC, maxammann approved these changes

2020-10-16 14:16 UTC, maxammann approved these changes

2020-10-16 14:55 UTC, merged